version: '3.6'
services:
  backend:
    stdin_open: true 
    tty: true        
    image: "$DOCKER_USER/backend:$BUILD_ID"
    container_name: node-js
    ports:
      - "3000:3000"
    networks:
      - net
networks:
  net:
